# Generated by Django 3.1.1 on 2020-09-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200904_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('expiredat', models.DateTimeField(blank=True, db_column='expiredAt', null=True)),
                ('createdat', models.DateTimeField(blank=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
            ],
            options={
                'db_table': 'Tokens',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Tokens',
        ),
    ]
